### PR TITLE
Remove the dependency on gvfs-bin, which was removed in Ubuntu groovy.

### PR DESCRIPTION
**Pull request by oSoMoN**

### CODE REVIEW

**Comment by oSoMoN** [comment]
Note that all the tools in gvfs-bin have been replaced by their "gio …" counterparts, but the package doesn't seem to contain any explicit call to gvfs tools, nor does it use xdg-open (which might require "gio open").
If depending on the gio binary is wanted, a dependency on libglib2.0-bin should be added.

**Comment by iainlane** [comment]
Just FYI, we need to upload this to unblock a new version of gvfs in Ubuntu. This change looks good to me, so I'm going to push it. Please merge the PR.

**Comment by iainlane** [comment]
Ah, I had to update the changelog too since there were other changes, please `git pull https://github.com/iainlane/ukui-desktop-environment.git update-changelog`

**Comment by handsome-feng** [comment]
Sorry for the delay, and merged!

**Pull request merged**
